<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libros, revistas, periodicos)>

    <!ELEMENT libros (libro+)>
    <!ELEMENT revistas (revista+)>
    <!ELEMENT periodicos (periodico+)>
    
    <!--dtd de libro-->
    <!--cambie el id a esa forma de ponerlo para que sea lo mas parecido
    a la forma de poner el id del ejercicio que vimos-->
    <!ELEMENT libro (tipo_clase, titulo,paginas_total,sinopsis, indice)>
    <!ATTLIST libro id CDATA #REQUIRED>

    <!ELEMENT tipo_clase (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT paginas_total (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
    <!ELEMENT indice (capitulo+)>

    <!ELEMENT capitulo (titulo_capitulo,paginas_capitulo,contenido)>
    <!ATTLIST capitulo id CDATA #REQUIRED>

    <!ELEMENT titulo_capitulo (#PCDATA)>
    <!ELEMENT paginas_capitulo (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>



    <!--dtd de revista-->
    <!--tuve que cambiar varias variables diferenciandoals de libro
    anadiendo _rev para que el sistema no las confundiese con
    las de libro-->
    <!ELEMENT revista (tipo_clase_rev, titulo_rev,paginas_total_rev,
    numero, indice_rev, seccion)>
    <!ATTLIST revista id CDATA #REQUIRED>

    <!ELEMENT tipo_clase_rev (#PCDATA)>
    <!ELEMENT titulo_rev (#PCDATA)>
    <!ELEMENT paginas_total_rev (#PCDATA)>
    <!ELEMENT  numero (#PCDATA)>
    <!ELEMENT indice_rev (#PCDATA)>

    <!ELEMENT seccion (numero_paginas_sec,contenido_sec)>
    <!ATTLIST seccion id CDATA #REQUIRED>

    
    <!ELEMENT numero_paginas_sec (#PCDATA)>
    <!ELEMENT contenido_sec (#PCDATA)>
    

   <!--dtd de PERIODICO-->

   <!ELEMENT periodico (tipo_clase_per, titulo_per,paginas_total_per,
   fecha_publi, indice_per, secciones)>
   <!ATTLIST periodico id CDATA #REQUIRED>

   <!ELEMENT tipo_clase_per (#PCDATA)>
   <!ELEMENT titulo_per (#PCDATA)>
   <!ELEMENT paginas_total_per (#PCDATA)>
   <!ELEMENT fecha_publi (#PCDATA)>
   <!ELEMENT indice_per (#PCDATA)>
   <!ELEMENT secciones (seccion_per+)>
 

   
   <!ELEMENT seccion_per (tipo_seccion, articulo)>
   <!ATTLIST tipo_seccion id CDATA #REQUIRED>

   <!ELEMENT tipo_seccion (#PCDATA)>

   
  
   <!ELEMENT articulo (autor,contenido_per)>

   <!ELEMENT autor (#PCDATA)>
   <!ELEMENT contenido_per (#PCDATA)>
]>




<biblioteca>
   <libros>

      <libro id= "L0001">
   
         <tipo_clase>Novela</tipo_clase>
         <titulo>La Comunidad del Anillo</titulo>
         <paginas_total> 256 </paginas_total>
         <sinopsis>El joven hobbit Frodo Bolsón emprende, en compañía de sus amigos, un peligroso
            viaje a Mordor para destruir el Anillo Único.
         </sinopsis>
         <indice>
            <capitulo id = "1">
               <titulo_capitulo>1. Una reunión muy esperada</titulo_capitulo>
               <paginas_capitulo>24</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             <capitulo id = "2">
               <titulo_capitulo>2. La sombra del pasado</titulo_capitulo>
               <paginas_capitulo>26</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             <capitulo id = "3">
               <titulo_capitulo>3. Tres es Compañía</titulo_capitulo>
               <paginas_capitulo>23</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             <capitulo id = "4">
               <titulo_capitulo>Un atajo hacia los hongos</titulo_capitulo>
               <paginas_capitulo>14</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             <capitulo id = "5">
               <titulo_capitulo>Conspiración desenmascarada</titulo_capitulo>
               <paginas_capitulo>17</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             <capitulo id = "6">
               <titulo_capitulo>El Bosque Viejo</titulo_capitulo>
               <paginas_capitulo>16</paginas_capitulo>
               <contenido>enlace a info</contenido>
             </capitulo>
             
            
         </indice>
      
      </libro>


   </libros>
  

 


<revistas>
   <revista id = "R0001">
     
      <tipo_clase_rev>otros</tipo_clase_rev>
      <titulo_rev>Retro Gamer</titulo_rev>
      <paginas_total_rev> 116 </paginas_total_rev>
      <numero>33</numero>
      
      <indice_rev>
         03.... Un Tributo a Paco Menéndez
         06.... Nueva Game &amp; Watch
         08.... Cierra el salón arcade de Sega
         09.... Libros
         10.... Alex Kidd in a Miracle World
         22.... 30 años de Monkey Island
         44.... Master System. Sus mejores juegos
         54.... Game Gear, la portátil de Sega
         64.... El retorno de Pokemon
         72.... Guía de Compras. Game Boy Color
         78.... Los 00s. Los años de los cibercafés
         84.... ...Windjammers
         87.... ...Double Dragon
         90.... ...Half Life
         94.... ...Daytona USA
         95.... ...Heimdall
         97.... ...La saga Tony Hawk
         100... ...Out Run
         102... ...Broken Sword
         105... ...The Legend of Zelda
         108... ...Crazy Taxi
         112... ...Radical Bikers
         114... Final Fantasy VII
      </indice_rev>
    
          <seccion id= "Retroradar">
             <numero_paginas_sec>9</numero_paginas_sec>
             <contenido_sec>enlace a contenido</contenido_sec>
          </seccion>
          <seccion id= "Reportajes">
            <numero_paginas_sec>70</numero_paginas_sec>
            <contenido_sec>enlace a contenido</contenido_sec>
         </seccion>
         <seccion id= "La historia de...">
            <numero_paginas_sec>30</numero_paginas_sec>
            <contenido_sec>enlace a contenido</contenido_sec>
         </seccion>
         <seccion id= "Pantalla final">
            <numero_paginas_sec>6</numero_paginas_sec>
            <contenido_sec>enlace a contenido</contenido_sec>
         </seccion>
      
   </revista>

</revistas>

  
<periodicos>
   <periodico id= "P0001">
      
      <tipo_clase_per>Nacional</tipo_clase_per>
      <titulo_per>El Mundo</titulo_per>
      <paginas_total_per> 50 </paginas_total_per>
      <fecha_publi>11 de Mayo de 2022</fecha_publi>

      <indice_per>
         02.... EDITORIAL. Alcaraz, un fuera de serie (Alberto Di Lolli)
         03.... OPINION. La guerra de los Depp (Esperanza Ruiz)
         04.... OPINION. La mentira y la posverdad (Miguel Ángel Quintana Paz)
         05.... OPINION. El menoscabo del mérito (Xavier Pericay)
         06.... ECONOMIA. El Elon Musk empresario (Pablo Pardo)
         08.... ECONOMIA. Toyota dispara un 27% su beneficio (Lorenzo Bernaldo de Quirós)
         12.... ECONOMIA. La banca cree que es buen momento para hipotecarse (Rocío Regidor)
         14.... INTERNACIONAL. Nueva Zelanda abrirá sus fronteras al 31 de Julio (Petra Fernández)
         17.... INTERNACIONAL. Finlandia presentará su solicitud de adhesión el Lunes (Casimiro Antúnez)
         20.... INTERNACIONAL. Arabia Saudí baja el precio del petróleo en Europa (Alejandra García)
         24.... DEPORTES. El Betis no afloja (Inma Valencia)
         26.... DEPORTES. Giro de Italia. Juanpe López hace historia (Lucas Sáez)
         29.... DEPORTES. Guardiola ya tiene a Haaland. (Francisco Cabezas)
         35.... CULTURA. La precuela de Juego de Tronos estrena trailer (Esther Miras)
         37.... CULTURA. El Festival de San Isidro anuncia sus conciertos (Adolfo Benítez)
         39.... CULTURA. Favoritos para Eurovision 2022 (Rosa Peláez)
         42.... CIENCIA. Eclipse lunar del 16 de Mayo. Lo que debes saber (Alex Ruiz)
         44.... CIENCIA. Descubren 30 exocometas en Beta Pictoris (Ana Miralles)
         48.... CIENCIA. Un problema de software obliga a retirar miles de coches eléctricos (Lucía Sánchez)
  
      </indice_per>

      <secciones>
          <seccion_per>
             <tipo_seccion id = "Económica"></tipo_seccion>
             <articulo>
                <autor>Pablo Pardo</autor>
                <contenido_per>enlace a contenido</contenido_per>
             </articulo>
             <articulo>
               <autor>Rocío Regidor</autor>
               <contenido_per>enlace a contenido</contenido_per>
            </articulo>
            <tipo_seccion id = "Opinión"></tipo_seccion>
            <articulo>
               <autor>Esperanza Ruiz/autor>
               <contenido_per>enlace a contenido</contenido_per>
            </articulo>
            <articulo>
              <autor>Miguel Ángel Quintana Paz</autor>
              <contenido_per>enlace a contenido</contenido_per>
           </articulo>
           </seccion_per>
           <tipo_seccion id = "Deportes"></tipo_seccion>
           <articulo>
              <autor>Inma Valencia</autor>
              <contenido_per>enlace a contenido</contenido_per>
           </articulo>
           <tipo_seccion id = "Nacional"></tipo_seccion>
           <articulo>
              <autor>Francisco Cabezaa</autor>
              <contenido_per>enlace a contenido</contenido_per>
           </articulo>
           <articulo>
             <autor>Daniel Lacalle</autor>
             <contenido_per>enlace a contenido</contenido_per>
          </articulo>
          <tipo_seccion id = "Internacional">Economica</tipo_seccion>
          <articulo>
             <autor>Casimiro García</autor>
             <contenido_per>enlace a contenido</contenido_per>
          </articulo>

      </secciones>
      
     </periodico>

</periodicos>
 
</biblioteca>